/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oop_database;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class chickInv extends javax.swing.JFrame {
    Connection con; 

    /**
     * Creates new form chickInv
     */
    public chickInv() {
        initComponents();
        String url = "jdbc:mysql://localhost:3306/sarisarisaya";
        String user = "root";
        String pass = "";
        try{
            con = DriverManager.getConnection(url,user,pass);
        }catch(Exception ex){
            System.out.println("Error : " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Jbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        invent_tble = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        CHICKENID = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_chickenID = new javax.swing.JTextField();
        txt_chickenpart = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        CHICKENQUANTITY = new javax.swing.JLabel();
        CHICKENSTOCK = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        viewtable = new javax.swing.JButton();
        txt_quantity = new javax.swing.JTextField();
        txt_stock = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jbtn.setBackground(new java.awt.Color(251, 255, 194));
        Jbtn.setFont(new java.awt.Font("Cooper Black", 0, 20)); // NOI18N
        Jbtn.setText("BACK");
        Jbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnActionPerformed(evt);
            }
        });

        invent_tble.setBackground(new java.awt.Color(231, 198, 179));
        invent_tble.setFont(new java.awt.Font("Cooper Black", 0, 15)); // NOI18N
        invent_tble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "CHICKEN ID", "CHICKEN PART", "QUANTITY", "STOCK DATE"
            }
        ));
        jScrollPane2.setViewportView(invent_tble);

        jLabel1.setFont(new java.awt.Font("Cooper Black", 1, 50)); // NOI18N
        jLabel1.setText(" INVENTORY");

        CHICKENID.setFont(new java.awt.Font("Cooper Black", 0, 20)); // NOI18N
        CHICKENID.setText("CHICKEN ID");

        jLabel2.setFont(new java.awt.Font("Cooper Black", 0, 20)); // NOI18N
        jLabel2.setText("CHICKEN PART");

        txt_chickenID.setFont(new java.awt.Font("Cooper Black", 0, 15)); // NOI18N

        txt_chickenpart.setFont(new java.awt.Font("Cooper Black", 0, 15)); // NOI18N

        jButton1.setBackground(new java.awt.Color(251, 255, 194));
        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        jButton1.setText("ADD");
        jButton1.setBorder(null);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        CHICKENQUANTITY.setFont(new java.awt.Font("Cooper Black", 1, 20)); // NOI18N
        CHICKENQUANTITY.setText("QUANTITY");

        CHICKENSTOCK.setFont(new java.awt.Font("Cooper Black", 1, 20)); // NOI18N
        CHICKENSTOCK.setText("STOCK DATE");

        jButton2.setBackground(new java.awt.Color(251, 255, 194));
        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        jButton2.setText("EDIT");
        jButton2.setBorder(null);
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        viewtable.setBackground(new java.awt.Color(251, 255, 194));
        viewtable.setFont(new java.awt.Font("Cooper Black", 1, 20)); // NOI18N
        viewtable.setText("VIEW TABLE");
        viewtable.setBorder(null);
        viewtable.setOpaque(false);
        viewtable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewtableActionPerformed(evt);
            }
        });

        txt_quantity.setFont(new java.awt.Font("Cooper Black", 0, 15)); // NOI18N
        txt_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_quantityActionPerformed(evt);
            }
        });

        txt_stock.setFont(new java.awt.Font("Cooper Black", 0, 15)); // NOI18N

        jButton3.setBackground(new java.awt.Color(251, 255, 194));
        jButton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 20)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.setBorder(null);
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/CHICKENINV.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(830, 830, 830)
                .addComponent(CHICKENQUANTITY))
            .addGroup(layout.createSequentialGroup()
                .addGap(870, 870, 870)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(630, 630, 630)
                .addComponent(viewtable, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1490, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(1000, 1000, 1000)
                .addComponent(txt_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(CHICKENID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(1330, 1330, 1330)
                .addComponent(Jbtn))
            .addGroup(layout.createSequentialGroup()
                .addGap(830, 830, 830)
                .addComponent(CHICKENSTOCK))
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(1000, 1000, 1000)
                .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(txt_chickenpart, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(700, 700, 700)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(440, 440, 440)
                .addComponent(txt_chickenID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1490, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(CHICKENQUANTITY)
                .addGap(96, 96, 96)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(viewtable, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(580, 580, 580)
                .addComponent(txt_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(CHICKENID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(840, 840, 840)
                .addComponent(Jbtn))
            .addGroup(layout.createSequentialGroup()
                .addGap(580, 580, 580)
                .addComponent(CHICKENSTOCK))
            .addGroup(layout.createSequentialGroup()
                .addGap(640, 640, 640)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(510, 510, 510)
                .addComponent(txt_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(420, 420, 420)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(580, 580, 580)
                .addComponent(txt_chickenpart, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(590, 590, 590)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(640, 640, 640)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(520, 520, 520)
                .addComponent(txt_chickenID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel3)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void JbtnActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
        chick chick = new chick();
        chick.setVisible(true);
    }                                    

    private void txt_quantityActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String sql ="DELETE FROM `chicken_inventory` WHERE  ChickenID =?";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) invent_tble.getModel();

            pst.setString(1,txt_chickenID.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "DELETED Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String sql ="UPDATE chicken_inventory SET ChickenPart =?, ChickenQuantity =?, ChickenStock =? WHERE ChickenID =?";
        try {
            PreparedStatement pst = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) invent_tble.getModel();

            pst.setString(4,txt_chickenID.getText());
            pst.setString(1,txt_chickenpart.getText());
            pst.setString(2,txt_quantity.getText());
            pst.setString(3,txt_stock.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "UPDATE Successfully");
        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String sql ="INSERT INTO chicken_inventory"
        + "(`ChickenID`, `ChickenPart`, `ChickenQuantity`, `ChickenStock`)"
        +"VALUES (?,?,?,?)";
        try{

            PreparedStatement pst  = con.prepareStatement(sql);

            DefaultTableModel model = (DefaultTableModel) invent_tble.getModel();

            pst.setString(1,txt_chickenID.getText());
            pst.setString(2,txt_chickenpart.getText());
            pst.setString(3,txt_quantity.getText());
            pst.setString(4,txt_stock.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Inserted Successfully");

        } catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }                                        

    private void viewtableActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        String sql = "SELECT * FROM  chicken_inventory";
        try{
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) invent_tble.getModel();
            model.setRowCount(0);

            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4)});
            }
        }catch(Exception ex){
            System.out.println("Error : " +ex.getMessage());
        }
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chickInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chickInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chickInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chickInv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chickInv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel CHICKENID;
    private javax.swing.JLabel CHICKENQUANTITY;
    private javax.swing.JLabel CHICKENSTOCK;
    private javax.swing.JButton Jbtn;
    private javax.swing.JTable invent_tble;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txt_chickenID;
    private javax.swing.JTextField txt_chickenpart;
    private javax.swing.JTextField txt_quantity;
    private javax.swing.JTextField txt_stock;
    private javax.swing.JButton viewtable;
    // End of variables declaration                   
}
